### ISSUE TITLE
Problems uploading files to Cloud Storage: com.google.cloud.storage.StorageException: Error writing request body to server

### ISSUE THREAD

**Issue by lingyun-zhu** [googleapis/google-http-java-client#1044]
Problems uploading files to Cloud Storage: com.google.cloud.storage.StorageException: Error writing request body to server #1526 

Problems uploading files to Cloud Storage: com.google.cloud.storage.StorageException: Error writing request body to server #3410

```
Caused by: java.io.IOException: Error writing request body to server
    at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3593)
    at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3576)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
    at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
    at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
    at java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:145)
    at com.google.api.client.util.ByteStreams.copy(ByteStreams.java:53)
    at com.google.api.client.util.IOUtils.copy(IOUtils.java:87)
    at com.google.api.client.http.AbstractInputStreamContent.writeTo(AbstractInputStreamContent.java:67)
    at com.google.api.client.http.GZipEncoding.encode(GZipEncoding.java:50)
    at com.google.api.client.http.HttpEncodingStreamingContent.writeTo(HttpEncodingStreamingContent.java:48)
    at com.google.api.client.http.javanet.NetHttpRequest$DefaultOutputWriter.write(NetHttpRequest.java:76)
    at com.google.api.client.http.javanet.NetHttpRequest.writeContentToOutputStream(NetHttpRequest.java:171)
    at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:117)
    at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
    at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequestWithoutGZip(MediaHttpUploader.java:551)
    at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequest(MediaHttpUploader.java:568)
    at com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:422)
    at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:336)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:551)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:475)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:592)
    at jp.co.fujixerox.cdspf.cmis.googledrive.object.CreateDocumentStrategy.execute(CreateDocumentStrategy.java:64)
    at jp.co.fujixerox.cdspf.cmis.googledrive.object.CreateDocumentStrategy.execute(CreateDocumentStrategy.java:24)
    at jp.co.fujixerox.cdspf.cmis.googledrive.strategy.GDriveRetryableAction.execute(GDriveRetryableAction.java:47)
    ... 48 common frames omitted
```

related message：
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:592)

**Comment by lingyun-zhu** [comment]
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:592)

It seems that something went wrong.The problem with googleapi like this, (this time is MediaHttpUploader) Is there any solution to the problem?

PS：【google-api-java-client】#1526         
          I posted the same question, only for different code.

**Comment by lingyun-zhu** [comment]
[Problems uploading files to Google drive: com.google.google.drive.java.io.IOException: Error writing request body to server #1047 ](url)

I‘m so sorry , No clarity has been expressed before, and new issue have been submitted.

**Comment by dxs516** [comment]
@lingyun-zhu : Is there a solution to this problem?
