### ISSUE TITLE
HttpResponse.disconnect() broken for ApacheHttpTransport

### ISSUE THREAD

**Issue by rawler** [googleapis/google-http-java-client#1303]
When using Apache as the underlying transport, issuing `response.getContent().close()` blocks waiting for the entire response to finish. If the source is the content from a GCS blob, this can potentially be many GB, which defeats the intention of `disconnect()`.

Calling `HttpResponse.disconnect()` before `.getContent().close()` falls on the problem that `disconnect()` [starts by calling `getContent().close()` before calling `LowLevelHttpHandler.disconnect()`](https://github.com/googleapis/google-http-java-client/blob/f17755cf5e8ccbf441131ebb13fe60028fb63850/google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java#L435). The wrong order, compared to the [intended way for ApacheHttpClient](https://www.baeldung.com/httpclient-cancel-request).

The net effect is that the application-code get's blocked until all the blob-content have been read and discarded.

**Comment by chanseokoh** [comment]
This is breaking us. When we call `httpResponse.disconnect()`, this makes the connection closed first. Not knowing that `ContentLengthInputStream` tries to consume and discard the remaining bytes in `close()`, and it throws an exception as `read()` returns -1 (end of stream) while there are remaining bytes.
```
 Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 2; received: 0)
 	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
 	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:198)
 	at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:101)
 	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:142)
 	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
 	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
 	at com.google.api.client.http.HttpResponse.ignore(HttpResponse.java:427)
 	at com.google.api.client.http.HttpResponse.disconnect(HttpResponse.java:441)
```

**Comment by chanseokoh** [comment]
A user can consistently [reproduce](https://github.com/GoogleContainerTools/jib/issues/3409#issuecomment-898665970) the above error just with 

```java
new ApacheHttpTransport().createRequestFactory()
    .reqFactory.buildGetRequest(new GenericUrl(url))
    .execute()
    .disconnect();
```
And if you look at the comments and thumbs-ups in the linked issue, there are a lot of users hitting this error.

I think until this error can be properly handled, we should revert the change in #1315.

**Comment by chanseokoh** [comment]
Oh, actually, I see #1409 already open.

**Comment by chanseokoh** [comment]
FTR, the early change has been reverted.

**Comment by Animeshz** [comment]
Hey, so this is not fixed yet.

This is causing unattributed bandwidth right now in our daily operations. This http client is still being used in the `hadoop-gcs-connector` and its causing full file reads when reading sequentially (https://github.com/GoogleCloudDataproc/hadoop-connectors/issues/1729).

If this issue is not fixed, can we reopen this and discuss possible fixes?
