### ISSUE TITLE
HttpMethods: add PATCH

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-http-java-client#167]
_From [yan...@google.com](https://code.google.com/u/111815493751521097215/) on November 19, 2012 13:22:24_

External references, such as a standards document, or specification? http://tools.ietf.org/html/rfc5789 Java environments (e.g. Java 6, Android 2.3, App Engine, or All)? All Please describe the feature requested. Google APIs make use of the HTTP PATCH verb, and there is an actual standard document behind it, so might as well add it to HttpMethods.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=167_

**Comment by qubic** [comment]
The patch method is unsupported again.
`	httpRequest = requestFactory.buildPatchRequest(new GenericUrl(url), jsonHttpContent);
	httpResponse = httpRequest.execute();`
The code above throw an exception:
`java.lang.IllegalArgumentException: HTTP method PATCH not supported
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:69)
	at com.google.api.client.http.javanet.NetHttpTransport.buildRequest(NetHttpTransport.java:133)
	at com.google.api.client.http.javanet.NetHttpTransport.buildRequest(NetHttpTransport.java:62)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:872)` 

I checked the code of NetHttpTransport.java
The variable "SUPPORTED_METHODS" missing patch method.

**Comment by shobhank** [comment]
This issue is still happening. Can you please point me to version that has PATCH support?

I still get error for PATCH
HTTP method PATCH not supported
at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:69)
at com.google.api.client.http.javanet.NetHttpTransport.buildRequest(NetHttpTransport.java:133)
at com.google.api.client.http.javanet.NetHttpTransport.buildRequest(NetHttpTransport.java:62)
at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:872)

**Comment by clementepereyra** [comment]
In case anyone still looking to solve this issue, there's a new way to do it.
Instead of using _com.google.api.client.http.javanet.NetHttpTransport_ use **com.google.api.client.http.apache.v2.ApacheHttpTransport**

You'll need to add the following dependency:
`<dependency>`
`                <groupId>com.google.http-client</groupId>`
`                <artifactId>google-http-client-apache-v2</artifactId>`
`                <version>1.34.0</version>`
`            </dependency>`

Where _1.34.0_ is the current latest version, though it would probably work with lower versions.

**Comment by patrickofriel-wk** [comment]
Is it possible to get Patch support in NetHttpTransport? ApacheHttpTransport has a bunch of extra "stuff" around connection pooling that we'd rather not deal with if possible
