### ISSUE TITLE
Proguard/r8 instructions missing

### ISSUE THREAD

**Issue by mtotschnig** [googleapis/google-http-java-client#1843]
From the Readme, I am following [Setup Instructions](https://googleapis.github.io/google-http-java-client/setup.html), then [Android](https://googleapis.github.io/google-http-java-client/android.html). Here it says "pay special attention to the Android instructions for [ProGuard](https://googleapis.github.io/google-http-java-client/setup.html#proguard)." but the referenced Proguard section does not exist.
I have been using this library with R8 successfully in the app, but recently tried out full mode, and got following exception:

```
Non-fatal Exception: java.lang.ExceptionInInitializerError:
       at java.lang.Class.newInstance(Class.java)
       at com.google.api.client.util.Types.newInstance(Types.java:113)
       at com.google.api.client.util.Data.newMapInstance(Data.java:550)
       at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:766)
       at com.google.api.client.json.JsonParser.parse(JsonParser.java:360)
       at com.google.api.client.json.JsonParser.parse(JsonParser.java:335)
       at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:79)
       at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:73)
       at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:460)
       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603)
       at org.totschnig.drive.sync.DriveServiceHelper.getFile(DriveServiceHelper.java:143)
       at org.totschnig.drive.sync.GoogleDriveBackendProvider.requireBaseFolder(GoogleDriveBackendProvider.kt:403)
       at org.totschnig.drive.sync.GoogleDriveBackendProvider.<init>(GoogleDriveBackendProvider.kt:420)
       at org.totschnig.drive.sync.GoogleDriveBackendProviderFactory.fromAccount(GoogleDriveBackendProviderFactory.kt:19)
       at org.totschnig.drive.sync.GoogleDriveBackendProviderFactory.fromAccount(GoogleDriveBackendProviderFactory.kt:12)
       at org.totschnig.myexpenses.sync.SyncBackendProviderFactory.from-0E7RQCE(SyncBackendProviderFactory.kt:18)
       at org.totschnig.myexpenses.sync.SyncBackendProviderFactory.access$from-0E7RQCE(SyncBackendProviderFactory.kt:12)
       at org.totschnig.myexpenses.sync.SyncBackendProviderFactory$Companion.get-0E7RQCE(SyncBackendProviderFactory.kt:41)
       at org.totschnig.myexpenses.sync.SyncAdapter.onPerformSync(SyncAdapter.kt:123)
       at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:354)

Caused by java.lang.IllegalArgumentException: unable to create new instance of class kc.a because it is abstract and because it has no accessible default constructor
       at com.google.api.client.util.Types.handleExceptionForNewInstance(Types.java:162)
       at com.google.api.client.util.Types.newInstance(Types.java:117)
       at com.google.api.client.util.Data.createNullInstance(Data.java:166)
       at com.google.api.client.util.Data.nullOf(Data.java:134)
       at com.google.api.services.drive.model.File.<clinit>(File.java:69)
       at java.lang.Class.newInstance(Class.java)
       at com.google.api.client.util.Types.newInstance(Types.java:113)
       at com.google.api.client.util.Data.newMapInstance(Data.java:550)
       at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:766)
       at com.google.api.client.json.JsonParser.parse(JsonParser.java:360)
       at com.google.api.client.json.JsonParser.parse(JsonParser.java:335)
       at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:79)
       at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:73)
       at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:460)
       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603)
       at org.totschnig.drive.sync.DriveServiceHelper.getFile(DriveServiceHelper.java:143)
       at org.totschnig.drive.sync.GoogleDriveBackendProvider.requireBaseFolder(GoogleDriveBackendProvider.kt:403)
       at org.totschnig.drive.sync.GoogleDriveBackendProvider.<init>(GoogleDriveBackendProvider.kt:420)
       at org.totschnig.drive.sync.GoogleDriveBackendProviderFactory.fromAccount(GoogleDriveBackendProviderFactory.kt:19)
       at org.totschnig.drive.sync.GoogleDriveBackendProviderFactory.fromAccount(GoogleDriveBackendProviderFactory.kt:12)
       at org.totschnig.myexpenses.sync.SyncBackendProviderFactory.from-0E7RQCE(SyncBackendProviderFactory.kt:18)
       at org.totschnig.myexpenses.sync.SyncBackendProviderFactory.access$from-0E7RQCE(SyncBackendProviderFactory.kt:12)
       at org.totschnig.myexpenses.sync.SyncBackendProviderFactory$Companion.get-0E7RQCE(SyncBackendProviderFactory.kt:41)
       at org.totschnig.myexpenses.sync.SyncAdapter.onPerformSync(SyncAdapter.kt:123)
       at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:354)

Caused by java.lang.InstantiationException: java.lang.Class<kc.a> cannot be instantiated
       at java.lang.Class.newInstance(Class.java)
       at com.google.api.client.util.Types.newInstance(Types.java:113)
       at com.google.api.client.util.Data.createNullInstance(Data.java:166)
       at com.google.api.client.util.Data.nullOf(Data.java:134)
       at com.google.api.services.drive.model.File.<clinit>(File.java:69)
       at java.lang.Class.newInstance(Class.java)
       at com.google.api.client.util.Types.newInstance(Types.java:113)
       at com.google.api.client.util.Data.newMapInstance(Data.java:550)
       at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:766)
       at com.google.api.client.json.JsonParser.parse(JsonParser.java:360)
       at com.google.api.client.json.JsonParser.parse(JsonParser.java:335)
       at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:79)
       at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:73)
       at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:460)
       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603)
       at org.totschnig.drive.sync.DriveServiceHelper.getFile(DriveServiceHelper.java:143)
       at org.totschnig.drive.sync.GoogleDriveBackendProvider.requireBaseFolder(GoogleDriveBackendProvider.kt:403)
       at org.totschnig.drive.sync.GoogleDriveBackendProvider.<init>(GoogleDriveBackendProvider.kt:420)
       at org.totschnig.drive.sync.GoogleDriveBackendProviderFactory.fromAccount(GoogleDriveBackendProviderFactory.kt:19)
       at org.totschnig.drive.sync.GoogleDriveBackendProviderFactory.fromAccount(GoogleDriveBackendProviderFactory.kt:12)
       at org.totschnig.myexpenses.sync.SyncBackendProviderFactory.from-0E7RQCE(SyncBackendProviderFactory.kt:18)
       at org.totschnig.myexpenses.sync.SyncBackendProviderFactory.access$from-0E7RQCE(SyncBackendProviderFactory.kt:12)
       at org.totschnig.myexpenses.sync.SyncBackendProviderFactory$Companion.get-0E7RQCE(SyncBackendProviderFactory.kt:41)
       at org.totschnig.myexpenses.sync.SyncAdapter.onPerformSync(SyncAdapter.kt:123)
       at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:354)
```

**Comment by suztomo** [comment]
Would you share the background of the problem? Which Google service were you trying to use?

**Comment by mtotschnig** [comment]
@suztomo Sorry for not following-up. I am using the Google Drive API, and was able to fix the problem by adding

-keep class com.google.api.services.drive.model.** { *; }

So the crash I mentioned does not belong here, but my point about the misleading documentation seems still valid to me.

**Comment by suztomo** [comment]
Thank you for update. Glad to hear you've resolved the problem.
