### ISSUE TITLE
Performance: JsonHttpContent.writeTo() is called twice for each HttpRequest

### ISSUE THREAD

**Issue by siom79** [googleapis/google-http-java-client#283]
Debugging shows that the method `JsonHttpContent.writeTo()` is called twice when a HttpRequest is rendered. For the first time it is called to compute the length of the body and for the second time to actually render the JSON string.

First invocation:

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at com.google.api.client.http.json.JsonHttpContent.writeTo(JsonHttpContent.java:73)
      at com.google.api.client.util.IOUtils.computeLength(IOUtils.java:113)
      at com.google.api.client.http.AbstractHttpContent.computeLength(AbstractHttpContent.java:139)
      at com.google.api.client.http.AbstractHttpContent.computeLength(AbstractHttpContent.java:117)
      at com.google.api.client.http.AbstractHttpContent.getLength(AbstractHttpContent.java:65)
      at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:914)
```

Second invocation:

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at com.google.api.client.http.json.JsonHttpContent.writeTo(JsonHttpContent.java:73)
      at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:79)
      at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
```

**Comment by andrey-qlogic** [comment]
@siom79 , @ajaaym this is not a bug or a feature. That code of the method [public long getLength() throws IOException](https://github.com/googleapis/google-http-java-client/blob/4b1f4b84caf21ae0731c01b476092e27c0c6c09c/google-http-client/src/main/java/com/google/api/client/http/AbstractHttpContent.java#L63)

works as expected. It calls the second method only once when contentLength is -1.

**Comment by andrey-qlogic** [comment]
@siom79, @ajaaym , @sduskis Please ignore my comment above.
It calls twice here https://github.com/googleapis/google-http-java-client/blob/8217035a79bfdc0f4a7193293a8583ee831ee25a/google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java#L1012 and here https://github.com/googleapis/google-http-java-client/blob/8217035a79bfdc0f4a7193293a8583ee831ee25a/google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java#L1076  because we need to calculate a Content-Length. Assume we could drop Content-Length when the length is known but it may not work then for  example for retry requests.

**Comment by andrey-qlogic** [comment]
@ejona86, @JustinBeckwith is the feature request still actual? by the log above I'm not clear about.

**Comment by sduskis** [comment]
@andrey-qlogic, yo usaw that the code gets called twice.  We should fix that.

**Comment by elharo** [comment]
I think #910 fixed this. Reopen if not.
