### ISSUE TITLE
Parsing JSON with unknown Enum

### ISSUE THREAD

**Issue by vtcosta** [googleapis/google-http-java-client#287]
Parsing JSON with unknown Enum will raise a NullPointerException:

```
Exception in thread "main" java.lang.NullPointerException
    at com.google.api.client.util.Data.parsePrimitiveValue(Data.java:440)
    at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:850)
    at com.google.api.client.json.JsonParser.parse(JsonParser.java:471)
    at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:780)
    at com.google.api.client.json.JsonParser.parse(JsonParser.java:471)
    at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:780)
    at com.google.api.client.json.JsonParser.parse(JsonParser.java:381)
    at com.google.api.client.json.JsonParser.parse(JsonParser.java:354)
    at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87)
    at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)
    at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:459)
```

It would be nice for that Enum property to be null when an unknown string is parsed, than to not being able to parse an object, and receive a NullPointerException.

**Comment by ejona86** [comment]
At the very least, it should be a better error.

**Comment by elharo** [comment]
Without breaking the API, this could throw a subclass of IOException.

Anyone have a sample unit test that demonstrates this problem?

**Comment by andrey-qlogic** [comment]
@vtcosta , @elharo 
The issue looks outdated. 
Checking the stringValue parameter for null in https://github.com/googleapis/google-http-java-client/blob/b4662209266ada78792e6ce6a82eb867e3d9988d/google-http-client/src/main/java/com/google/api/client/util/Data.java#L406 , 

and throwing an IllegalArgumentException if the enum is unknown https://github.com/googleapis/google-http-java-client/blob/b4662209266ada78792e6ce6a82eb867e3d9988d/google-http-client/src/main/java/com/google/api/client/util/Data.java#L449

**Comment by andrey-qlogic** [comment]
@sduskis, reopened until PR with unit test for unknown enum merged.

**Comment by tenaciousRas** [comment]
There was some miscommunication here and the feature-request should be considered current, not outdated, imho.

The request asks that an exception _not_ be thrown.  The request does not ask to have IllegalArgumentException thrown instead of NullPointerException.  The feature-request is not concerned with what happens with null values of known enum properties.

Maybe a change to the key annotation would satisfy the request -- something like:  `@Key([key_name : string], [throw_exception : bool])`.  Another way would be to not throw an exception in this case (and other similar ones).  I'm not sure why the parsing implementation kills the parser when a single field can't be hydrated.
