### ISSUE TITLE
Api 19  Caused by: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets

### ISSUE THREAD

**Issue by Zevsus** [googleapis/google-http-java-client#926]
#### Environment details

2. OS type and version: Android api 19
3. Java version: 8
4. google-http-client version(s):  implementation 'com.google.http-client:google-http-client-gson:1.34.0'

#### Code example
private static List<File> exeQ(String q) throws IOException {
        String nextPageToken = "";
        List<File> res = new ArrayList<>();
        do {
            final FileList list = googleDriveService.files().list().setSpaces("drive").setQ(q).setPageToken(nextPageToken).setFields("nextPageToken, files(*)").setPageSize(100).setOrderBy("modifiedTime").execute();
            nextPageToken = list.getNextPageToken();
            res.addAll(list.getFiles());
        } while (nextPageToken != null);
        return res;
    }

#### Stack trace
```
     Caused by: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
        at com.google.api.client.util.escape.CharEscapers.decodeUriPath(CharEscapers.java:110)
        at com.google.api.client.http.GenericUrl.toPathParts(GenericUrl.java:594)
        at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:200)
        at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:177)
        at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:126)
        at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:109)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequestUrl(AbstractGoogleClientRequest.java:388)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:423)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:542)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:475)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:592)
        (GFile.java:192)
```
Thanks!

**Comment by codyoss** [comment]
From what I can tell StandardCharsets was added in with api level 19, so this should work. 
Ref: https://developer.android.com/reference/java/nio/charset/StandardCharsets.html

**Comment by Zevsus** [comment]
But it crashes - in the previous version this was not.

**Comment by codyoss** [comment]
Is your target >19?

**Comment by insightfulfellow** [comment]
I have the same problem.  The min required API has not changed, but now it depends on
`java.nio.charset.StandardCharsets` which requires API > 19.  This dependency should be removed.

**Comment by elharo** [comment]
Per android docs, java.nio.charset.StandardCharsets was added in API 19, and requires API >= 19, not strictly greater than 19:

https://developer.android.com/reference/java/nio/charset/StandardCharsets

Are you stating that the docs are wrong? (Entirely possible, of course, but I want to make sure there isn't some other confusion here.)

**Comment by 3c71** [comment]
2 weeks ago I was able to use this API on Android 4.2, but now I get this error. Is this API no longer supporting API below 19?

**Comment by elharo** [comment]
Correct. We do not support Android before 4.4.

**Comment by 3c71** [comment]
It seems the library does not support Android before 4.4 only because of this charset class missing that was added in API 19 which only an UTF8 name?

Anyway I reverted to version 1.33.0 of httpclient and version 1.30.1 of apiclient and "all is good" now and it appears to be working on all Android 4.x. Is that correct assumption?

Wouldn't it be possible to include the minimum SDK in the library so we get a warning if we target a lower SDK? Other libraries are doing so and it could avoid bad surprises in production.

**Comment by elharo** [comment]
I'm not sure. I'm hardly an expert in Android. Is there some standard way to do this? E.g. by adding a property to MANIFEST.MF or some such?

**Comment by 3c71** [comment]
Sure there is a minSdk="" in AndroidManifest.xml that exists for any Android module, apps or libraries.

As a matter of fact I looked at https://github.com/googleapis/google-http-java-client/blob/master/google-http-client-android/AndroidManifest.xml

and it shows this:
        android:minSdkVersion="4"
        android:targetSdkVersion="4" 

It should read 14 and not 4. I suppose other libraries are affected the same way but I didn't check.

No wonder there is no warning or error.
