### ISSUE TITLE
Incorrect check for Windows (case sensitivity)

### ISSUE THREAD

**Issue by brianfromoregon** [googleapis/google-http-java-client#953]
The value for StandardSystemProperty.OS_NAME on win10 is "Windows 10" which fails the case sensitive startsWith check

See https://github.com/googleapis/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/util/store/FileDataStoreFactory.java#L55

**Comment by brianfromoregon** [comment]
If I change it locally to be case insensitive, I see this (again on win10)
```

java.nio.file.attribute.UserPrincipalNotFoundException: null
	at sun.nio.fs.WindowsUserPrincipals.lookup(WindowsUserPrincipals.java:147) ~[?:?]
	at sun.nio.fs.WindowsFileSystem$LookupService$1.lookupPrincipalByName(WindowsFileSystem.java:244) ~[?:?]
	at com.google.api.client.util.store.FileDataStoreFactory.setPermissionsToOwnerOnlyWindows(FileDataStoreFactory.java:158) ~[main/:1.32.1]
	at com.google.api.client.util.store.FileDataStoreFactory.<init>(FileDataStoreFactory.java:71) ~[main/:1.32.1]

```

**Comment by MartijnWoudstra** [comment]
Furthermore, the `.lookupPrincipalByName("OWNER@");` seems to be throwing the `UserPrincipalNotFoundException`
